version: '3'

services:
  selenoid:
    image: aerokube/selenoid
    container_name: selenoid
    # command: -listen :4444 -limit 10 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -timeout 3m0s -container-network selenoid
    command: -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -timeout 3m0s -container-network selenoid
    ports:
      - "4445:4444"
    volumes:
      - "$PWD:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      selenoid: null

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444"]
    networks:
      selenoid: null

  maven:
    build:
      context: image/maven
    container_name: maven
    volumes:
      - .:/app
    working_dir: /app
    command: [ "mvn", "clean", "test", "-e", "-X" ]
    networks:
      selenoid: null

networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created